# site settings
title: Endeveloper's
subtitle: Official
email: endevs.contact@gmail.com
description: We are commited to attain superiority in the educational field of programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://endevelopers.github.io" # the base hostname & protocol for your site
author: Endeveloper's
street_address: Banaba St. Phase 5 Greenwoods Executive Village
city: Cainta
state: Rizal
zip_code: 1900
country: Philippines
phone: (0927) 824-7966

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Endevelopers
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/profile.php?id=100089827724947&mibextid=LQQJ4d
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- test.ps1
